Article.create!([
  {title: "How to look amazing", body: "Eat kale, lots of kale", lead: "Click here", image: "https://www.google.com/some_image_path.png/", category_id: 1, slug: "how-to-look-amazing", author_id: 1}
])
Author.create!([
  {name: "Angus Tasker", title: "CEO", image: "https://www.someimagepath.com/"}
])
Category.create!([
  {description: "Aesthetics", slug: "aesthetics"},
  {description: "Allergies and Immunity", slug: "allergies-and-immunity"},
  {description: "Antiaging and Longevity", slug: "antiaging-and-longevity"},
  {description: "Antioxidant and Anti-inflammatory", slug: "antioxidant-and-anti-inflammatory"},
  {description: "Bone and Joint Health", slug: "bone-and-joint-health"},
  {description: "Cardiovascular", slug: "cardiovascular"},
  {description: "Cognitive Function and Brain Health", slug: "cognitive-function-and-brain-health"},
  {description: "Energy and Stimulation", slug: "energy-and-stimulation"},
  {description: "Eye Health", slug: "eye-health"},
  {description: "Fat Loss", slug: "fat-loss"},
  {description: "General Health", slug: "general-health"},
  {description: "Gut Health", slug: "gut-health"},
  {description: "Insulin Sensitivity", slug: "insulin-sensitivity"},
  {description: "Libido and Sexual Health", slug: "libido-and-sexual-health"},
  {description: "Liver Health and Detoxification", slug: "liver-health-and-detoxification"},
  {description: "Men's Health", slug: "men-s-health"},
  {description: "Mood", slug: "mood"},
  {description: "Muscle Gain and Exercise", slug: "muscle-gain-and-exercise"},
  {description: "Sleep", slug: "sleep"},
  {description: "Testosterone Boosting", slug: "testosterone-boosting"},
  {description: "Women's Health", slug: "women-s-health"}
])
Supplement.create!([
  {name: "Acorus calamus", aka: "Sweet Flag, Golomi, Ugragandha, Vacha, Vekhanda, Bach, Calamus Oil", category_id: 7, slug: "acorus-calamus"},
  {name: "Adrafinil", aka: "Olmifon, CRL-40028", category_id: 8, slug: "adrafinil"},
  {name: "Aframomum melegueta", aka: "Grains of Paradise, melegueta pepper, alligator pepper, Guinea pepper, Guinea grain", category_id: 10, slug: "aframomum-melegueta"},
  {name: "Agmatine", aka: "Clonidine-displacing substance, 4-(aminobutyl)guanidine, Decarboxylated arginine", category_id: 17, slug: "agmatine"},
  {name: "Alanine", aka: "", category_id: 18, slug: "alanine"},
  {name: "Alanylglutamine", aka: "L-Alanyl-L-Glutamine, Alanyl-Glutamine, Sustamine (brand name)", category_id: 18, slug: "alanylglutamine"},
  {name: "Alcohol", aka: "Ethanol, Drinking alcohol, Beer, Gin, Vodka, Wine, Jager", category_id: 7, slug: "alcohol"},
  {name: "Aloe vera", aka: "Aloe Barbadensis", category_id: 12, slug: "aloe-vera"},
  {name: "Alpha-GPC", aka: "Alpha-glycerylphosphorylcholine, L-alpha-glycerophosphocholin, glycerophosphocholine, L-alpha-glyceryl-phosphorylcholine, Choline Alphoscerate", category_id: 7, slug: "alpha-gpc"},
  {name: "Alpha-Lipoic Acid", aka: "ALA, thioctic acid, 1, 2-dithiolane-3-pentanoic acid, ala, Tiolepta", category_id: 4, slug: "alpha-lipoic-acid"},
  {name: "Amaranth", aka: "Amaranthus", category_id: 4, slug: "amaranth"},
  {name: "Anacyclus pyrethrum", aka: "Akarkara, Vajikaran Rasayana, Pellitory Root, Spanish Chamomile, pyrethrin", category_id: 14, slug: "anacyclus-pyrethrum"},
  {name: "Anatabine", aka: "Anatabloc (Brand Name)", category_id: 4, slug: "anatabine"},
  {name: "Andrographis paniculata", aka: "Chiretta, King of Bitters, Kalmegh, Creat, Chuanxinlian, Yijianxi, Lanhelian, Indian Echinacea", category_id: 2, slug: "andrographis-paniculata"},
  {name: "Anethum graveolens", aka: "Dill, Lao coriander, Pakchee Lao", category_id: 21, slug: "anethum-graveolens"},
  {name: "Angelica gigas", aka: "Dang Gui, Korean Dang Gui, Cham-Dang-Gui", category_id: 4, slug: "angelica-gigas"},
  {name: "Aniracetam", aka: "1-p-anisoyl-2-pyrrilidinone, Ro 13-5057, CAS 72432-10-1, 1(4-methoxybenzoyl)-2-pyrrolidinone", category_id: 7, slug: "aniracetam"},
  {name: "Apigenin", aka: "4&prime;, 5, 7, -trihydroxyflavone, biapigenin (a dimer found in nature)", category_id: 17, slug: "apigenin"},
  {name: "Apocynum venetum", aka: "Luobuma, Dogbane, Chinse Dogbane, Herbal for Relief of Famines, Rafuma", category_id: 17, slug: "apocynum-venetum"},
  {name: "Apple Cider Vinegar", aka: "ACV", category_id: 13, slug: "apple-cider-vinegar"},
  {name: "Arachidonic acid", aka: "", category_id: 18, slug: "arachidonic-acid"},
  {name: "Arginine", aka: "L-Arginine", category_id: 18, slug: "arginine"},
  {name: "Aromatherapy", aka: "", category_id: 19, slug: "aromatherapy"},
  {name: "Aronia melanocarpa", aka: "Chokeberry, Black Apple Berry, RowanBerry (hybrids with Aronia), Aronox (Brand Name)", category_id: 4, slug: "aronia-melanocarpa"},
  {name: "Artemisia iwayomogi", aka: "Haninjin, Mugwort (refers to the family of Artemisia)", category_id: 4, slug: "artemisia-iwayomogi"},
  {name: "Artichoke Extract", aka: "Artichoke", category_id: 12, slug: "artichoke-extract"},
  {name: "Ascophyllum nodosum", aka: "Kelp (one of many species), Egg Wrack, Rockweed", category_id: 4, slug: "ascophyllum-nodosum"},
  {name: "Ashwagandha", aka: "Withania Somnifera, Indian Ginseng, Smell of Horse, Winter Cherry, Dunal, Solanaceae", category_id: 17, slug: "ashwagandha"},
  {name: "Asparagus racemosus", aka: "Asparagus, Asparagus Extract, Shatavari", category_id: 12, slug: "asparagus-racemosus"},
  {name: "Astaxanthin", aka: "Cardax (Disodium Disuccinate Astaxanthin), 3, 3&prime;-dihydroxy-b, b-carotene-4, 4&prime;-dione", category_id: 4, slug: "astaxanthin"},
  {name: "Asteracantha longifolia", aka: "Hygrophila longifolia, Barleria auriculata, Barleria spinosa, Ikshura, Ikshugandha, Hygrophila spinosa, Hygrophila auriculata, Kokilaaksha, Talimakhana, gokulakanta, marsh barbel", category_id: 15, slug: "asteracantha-longifolia"},
  {name: "Astragalus membranaceus", aka: "Astragalus, huangqi, (A component of) Danggui buxue tang (DBT), membranous milk-vetch root, ogi, Huang Qi, TA-65, TAT2", category_id: 3, slug: "astragalus-membranaceus"},
  {name: "Ayurveda", aka: "Ayurvedic Medicine, Traditional Indian Medicine", category_id: 11, slug: "ayurveda"},
  {name: "BPC-157", aka: "PL 14736, PL-10, Bepecin", category_id: 5, slug: "bpc-157"},
  {name: "Bacopa monnieri", aka: "Brahmi, Aindri, Lysimachia monnieri L. Cent., Graticola monnieri L., Herpestis monniera L. Kunth., Water hyssop, Thyme-leafed gratiola, Indian Pennywort, Jalabrahmi", category_id: 7, slug: "bacopa-monnieri"},
  {name: "Banaba Leaf", aka: "Crape Myrtle, Crepe Myrtle, Lagerstroemia, Banaba", category_id: 13, slug: "banaba-leaf"},
  {name: "Basella alba", aka: "Indian Spinach, Malabar spinach, Red vine spinach, Creeping Spinach", category_id: 20, slug: "basella-alba"},
  {name: "Beet Root", aka: "Beetroot juice, Beet, Beetroot, beetroot", category_id: 18, slug: "beet-root"},
  {name: "Benfotiamine", aka: "S-{(Z)-2-{(4-amino-2-methylpyrimidin-5-yl) methyl-formylamino}-5-phosphonooxypent-2-en-3-yl} benzenecarbothioate", category_id: 4, slug: "benfotiamine"},
  {name: "Berberine", aka: "", category_id: 13, slug: "berberine"},
  {name: "Beta-Alanine", aka: "b-alanine, &beta;-alanine, carnosine precursor", category_id: 18, slug: "beta-alanine"},
  {name: "Betalains", aka: "Beet pigments, Betalain, betanin, betanidin, phyllocactin, indicaxanthin, hylocerenin, 2', O-Apiosylphyllocactin,", category_id: 18, slug: "betalains"},
  {name: "Biotin", aka: "Vitamin B7, Vitamin H", category_id: 1, slug: "biotin"},
  {name: "Black Cohosh", aka: "Cimicifuga racemosa, Bugbane, Bugroot, Snakeroot, Rattleroot, Blackroot, Black Snake Root", category_id: 21, slug: "black-cohosh"},
  {name: "Black Pepper", aka: "Piper Nigrum, Piperaceae, Piperine", category_id: 4, slug: "black-pepper"},
  {name: "Bladderwrack", aka: "Fucus Vesiculosis", category_id: 4, slug: "bladderwrack"},
  {name: "Blueberry", aka: "Blueberries, Blue berries", category_id: 7, slug: "blueberry"},
  {name: "Boerhaavia diffusa", aka: "Punarnava", category_id: 13, slug: "boerhaavia-diffusa"},
  {name: "Boron", aka: "", category_id: 20, slug: "boron"},
  {name: "Boswellia serrata", aka: "Indian Frankincense, Salai, Salai Guggul, Gajabhakshya", category_id: 5, slug: "boswellia-serrata"},
  {name: "Branched Chain Amino Acids", aka: "BCAAs, BCAA", category_id: 18, slug: "branched-chain-amino-acids"},
  {name: "Brassaiopsis glomerulata", aka: "", category_id: 20, slug: "brassaiopsis-glomerulata"},
  {name: "Brassica vegetables", aka: "Broccoli, Cauliflower, Brussel Sprouts, Kale, etc.", category_id: 15, slug: "brassica-vegetables"},
  {name: "Brassinosteroids", aka: "", category_id: 18, slug: "brassinosteroids"},
  {name: "Bromelain", aka: "Pineapple extract", category_id: 12, slug: "bromelain"},
  {name: "Bryonia laciniosa", aka: "Shivlingi, Diplocyclos Palmatus, Byrony Root", category_id: 20, slug: "bryonia-laciniosa"},
  {name: "Bulbine natalensis", aka: "ibhucu, rooiwortel, ingcelwane", category_id: 20, slug: "bulbine-natalensis"},
  {name: "Butea monosperma", aka: "Butea frondosa, Erythrina monosperma, Plaso monosperma, The Treasurer of the Gods and of Sacrifice, kimsuk, muriku, moduga, Bastard Teak, Dhak, Palash, Flame of the Forest, Pal&#259;&#347;a", category_id: 5, slug: "butea-monosperma"},
  {name: "Butea superba", aka: "Red Kwao Krua", category_id: 14, slug: "butea-superba"},
  {name: "CBD", aka: "Cannabidiol, Epidiolex", category_id: 17, slug: "cbd"},
  {name: "CDP-choline", aka: "Citicholine, Cytidine Diphosphocholine", category_id: 7, slug: "cdp-choline"},
  {name: "Caesalpinia benthamiana", aka: "Mezoneuron benthamianum", category_id: 14, slug: "caesalpinia-benthamiana"},
  {name: "Caffeine", aka: "Coffee extract, Tea extract, 1, 3, 7-Trimethylxanthine, Liquid crack", category_id: 8, slug: "caffeine"},
  {name: "Calcium", aka: "Ca2+, Ca, Coral Calcium", category_id: 5, slug: "calcium"},
  {name: "Calcium-D-Glucarate", aka: "Calcium Glucarate, Saccharic acid, Calcium-D-Saccharate, Glucaric acid", category_id: 15, slug: "calcium-d-glucarate"},
  {name: "Capsaicin", aka: "Chili extract, Hot pepper extract, trans-8-methyl-N-Vanilyl-6-nonenamide, Capsaicinoids", category_id: 10, slug: "capsaicin"},
  {name: "Capsicum Carotenoids", aka: "Capsorubin, Capsanthin", category_id: 5, slug: "capsicum-carotenoids"},
  {name: "Caralluma fimbriata", aka: "Slimaluma (Brand Name)", category_id: 10, slug: "caralluma-fimbriata"},
  {name: "Casein", aka: "Casein", category_id: 18, slug: "casein"},
  {name: "Celastrus paniculatus", aka: "Jyothismati Oil, Celastrus Oil, Malkanguni Oil, The Elixir of Life", category_id: 7, slug: "celastrus-paniculatus"},
  {name: "Celery seed extract", aka: "Apium graveolens, Celery", category_id: 4, slug: "celery-seed-extract"},
  {name: "Centella asiatica", aka: "Gotu kola, Indian Pennywort, Jal Brahmi and Mandookaparni, Brahmi, Tsubokusa", category_id: 7, slug: "centella-asiatica"},
  {name: "Centrophenoxine", aka: "Centro, Lucidril (Brand Name)", category_id: 7, slug: "centrophenoxine"},
  {name: "Chlorella", aka: "Chlorella pyrenoidosa", category_id: 15, slug: "chlorella"},
  {name: "Chlorogenic Acid", aka: "Coffee bean extract, 5-O-caffeoylquinic acid, 3-O-caffeoylquinic acid Green coffee extract", category_id: 10, slug: "chlorogenic-acid"},
  {name: "Chlorophytum borivilianum", aka: "Safed Musli, Safed Moosli", category_id: 14, slug: "chlorophytum-borivilianum"},
  {name: "Choline", aka: "Trimethylethanolamine, Choline Bitartrate", category_id: 7, slug: "choline"},
  {name: "Chondroitin", aka: "Condrosulf (Brand Name)", category_id: 5, slug: "chondroitin"},
  {name: "Chromium", aka: "", category_id: 13, slug: "chromium"},
  {name: "Chrysin", aka: "Propolis, Honey extract, Passiflora caerulea Linn", category_id: 20, slug: "chrysin"},
  {name: "Cinnamon", aka: "Chinese (Saigon) cinnamon, Cassia Cinnamon, Indonesian (Ceylon/True) Cinnamon", category_id: 13, slug: "cinnamon"},
  {name: "Cissus quadrangularis", aka: "Harjor, Asthi Shrinkhala, Bone Setter", category_id: 5, slug: "cissus-quadrangularis"},
  {name: "Citric Acid", aka: "Citrate", category_id: 11, slug: "citric-acid"},
  {name: "Citrulline", aka: "L-Citrulline, Stimol (Brand Name), Watermelon extract", category_id: 18, slug: "citrulline"},
  {name: "Citrullus colocynthis", aka: "Bitter apple, desert gourd, bitter cucumber", category_id: 13, slug: "citrullus-colocynthis"},
  {name: "Clenbuterol", aka: "Clen, 4-amino-alpha(t-butyl-amino)methyl-3, 5-dichlorobenzyl alcohol", category_id: 10, slug: "clenbuterol"},
  {name: "Clitoria ternatea", aka: "Shankapushi, Shankapushpi, Butterfly Pea", category_id: 7, slug: "clitoria-ternatea"},
  {name: "Clubmoss", aka: "Lycopodium clavatum, Devil's Ash, Devil's Claw, Ground Pine, Toothed Clubmoss", category_id: 7, slug: "clubmoss"},
  {name: "Cnidium monnieri", aka: "Shechuangzi, Osthole, Jashoshi, Cnidii Fructus (Fruits of Cnidium)", category_id: 14, slug: "cnidium-monnieri"},
  {name: "Cocoa Extract", aka: "Chocolate polyphenols, Cocoa polyphenols, Cacao polyphenols, Cacao extract, Chocamine", category_id: 6, slug: "cocoa-extract"},
  {name: "Coconut Oil", aka: "Cocos nucifera, Coconut, Medium Chain Triglycerides (partially synonymous but commonly touted as such)", category_id: 1, slug: "coconut-oil"},
  {name: "Codonopsis pilosula", aka: "Dangshen, Dang Shen", category_id: 7, slug: "codonopsis-pilosula"},
  {name: "Coenzyme Q10", aka: "CoQ10, Ubiquinone, Ubiquinol, trans 2, 3-dimethoxy-5-methyl-6-decaprenyl-1, 4-benzoquinone", category_id: 6, slug: "coenzyme-q10"},
  {name: "Coffee", aka: "Liquid gold", category_id: 8, slug: "coffee"},
  {name: "Cold Exposure", aka: "Non-shivering thermogenesis, Shivering", category_id: 10, slug: "cold-exposure"},
  {name: "Coleus forskohlii", aka: "Forskolin, Coleonol, 7beta-acetoxy-1alpha, 6beta, 9alpha-trihydroxy-8, 13-epoxy-labd-14-en-11-one", category_id: 10, slug: "coleus-forskohlii"},
  {name: "Colostrum", aka: "First Milk, Bovine colostrum", category_id: 2, slug: "colostrum"},
  {name: "Coluracetam", aka: "MKC-231, BCI-540, 2-(2-oxopyrrolidin-1-yl)-N-(2, 3-dimethyl-5, 6, 7, 8-tetrahydrofuro2, 3-b quinolin-4-yl)acetoamide", category_id: 7, slug: "coluracetam"},
  {name: "Conjugated Linoleic Acid", aka: "CLA, Rumenic Acid", category_id: 10, slug: "conjugated-linoleic-acid"},
  {name: "Convolvulus pluricaulis", aka: "Shankhapushpi", category_id: 7, slug: "convolvulus-pluricaulis"},
  {name: "Copper", aka: "", category_id: 4, slug: "copper"},
  {name: "Cordyceps", aka: "Cordyceps Sinensis, Cordyceps Militaris, Caterpillar Fungus, Cetepiller Mushroom, Summer grass-winter worm, Totsu kasu, Yarchakunbu, Aweto", category_id: 14, slug: "cordyceps"},
  {name: "Crataegus pinnatifida", aka: "Chinese Hawthorn, Shanzha, Shanlihong, Yixintong (tablets)", category_id: 4, slug: "crataegus-pinnatifida"},
  {name: "Creatine", aka: "creatine monohydrate, creatine 2-oxopropanoate, a-methylguanidinoacetic acid", category_id: 18, slug: "creatine"},
  {name: "Creatinol O-Phosphate", aka: "COP, Creatinolphosphate, Aplodan", category_id: 6, slug: "creatinol-o-phosphate"},
  {name: "Cucurbita pepo", aka: "Pumpkin extract, pumpkin seed oil", category_id: 4, slug: "cucurbita-pepo"},
  {name: "Curcumin", aka: "Turmeric extract, Curry Extract, Curcuma, Diferuloylmethane, JiangHuang, Curcuma Longa, 1, 7-bis-{3-methoxy-4-hydroxyphenyl}-1, 6-heptadiene-3, 5-dione", category_id: 4, slug: "curcumin"},
  {name: "Cyanidin", aka: "Cyanidin-3-Glucoside, C3G, Cyanidin-3-Rutinoside", category_id: 13, slug: "cyanidin"},
  {name: "D-Aspartic Acid", aka: "D-AA, D-Aspartate, DAA", category_id: 20, slug: "d-aspartic-acid"},
  {name: "D-Ribose", aka: "", category_id: 18, slug: "d-ribose"},
  {name: "D-Serine", aka: "", category_id: 7, slug: "d-serine"},
  {name: "DMAE", aka: "Dimethylaminoethanol, dimethylethanolamine, Deanol (cream)", category_id: 7, slug: "dmae"},
  {name: "Dactylorhiza hatagirea", aka: "Early Marsh Orchid, Salam Panja, Hatta Haddi, orchis macula, Wang lak, Lovha, Hathejadi, Panchaule, Airula", category_id: 14, slug: "dactylorhiza-hatagirea"},
  {name: "Damiana Leaf", aka: "Tunera Diffusa, Tunera Aphrodisiaca", category_id: 14, slug: "damiana-leaf"},
  {name: "Dark Therapy", aka: "", category_id: 19, slug: "dark-therapy"},
  {name: "Dehydroepiandrosterone", aka: "DHEA, Pradesterone, Hydroxyandrosterone, 3&beta;-Hydroxy-5-Androstene-17-one", category_id: 20, slug: "dehydroepiandrosterone"},
  {name: "Dendrobium", aka: "", category_id: 12, slug: "dendrobium"},
  {name: "Diindolylmethane", aka: "DIM, 3, 3'-diindolylmethane", category_id: 4, slug: "diindolylmethane"},
  {name: "Dimocarpus longan", aka: "Euphoria Longan, Dragon Eye, Soapberry", category_id: 7, slug: "dimocarpus-longan"},
  {name: "Dioscorea villosa", aka: "Wild Yam", category_id: 21, slug: "dioscorea-villosa"},
  {name: "ECA", aka: "Ephedrine/Caffeine/Aspirin, ECA Stack, EC Stack", category_id: 10, slug: "eca"},
  {name: "Ecdysteroids", aka: "Suma extract, pfaffia extract, Brazilian ginseng extract, beta-ecdysterone, turkesterone, ecdysterone", category_id: 18, slug: "ecdysteroids"},
  {name: "Echinacea", aka: "Brauneria purpurea, Echinacea intermedia, Rudbeckia purpurea, Purple coneflower herb, Coneflower, red sunflower", category_id: 2, slug: "echinacea"},
  {name: "Ecklonia cava", aka: "", category_id: 4, slug: "ecklonia-cava"},
  {name: "Eclipta alba", aka: "False Daisy, Yerba de tago, Kehraj, Karisalankanni", category_id: 15, slug: "eclipta-alba"},
  {name: "Eggs", aka: "Ovum, Ova, Eggs, Egg", category_id: 11, slug: "eggs"},
  {name: "Eleutherococcus senticosus", aka: "Siberian ginseng, Ciwujia, Acanthopanax senticosus, Eleuthero", category_id: 18, slug: ""},
  {name: "Emblica officinalis", aka: "Phyllanthus emblica, Amla, Anwala, Indian gooseberry", category_id: 13, slug: "emblica-officinalis"},
  {name: "Energy Drinks", aka: "Redbull Energy Drink, Monster Energy Drink, Full Throttle Energy Drink, NOS Energy Drink", category_id: 8, slug: "energy-drinks"},
  {name: "Ephedrine", aka: "Ephedra Vulgaris, Ephedraceae, ma huang", category_id: 10, slug: "ephedrine"},
  {name: "Eriobotrya japonica", aka: "Loquat, Biwa, Pipa, pipaye, chinese plum, japanese plum", category_id: 2, slug: "eriobotrya-japonica"},
  {name: "Eschscholzia californica", aka: "California Poppy", category_id: 7, slug: "eschscholzia-californica"},
  {name: "Eucommia ulmoides", aka: "Du Zhong, Gutta-Percha, Rubber Bark tree, Tochu", category_id: 4, slug: "eucommia-ulmoides"},
  {name: "Euonymus alatus", aka: "Winged Euonymus, Celastraceae, Gui Jeon Wu, Burning Bush", category_id: 6, slug: "euonymus-alatus"},
  {name: "Eurycoma Longifolia Jack", aka: "Longjack, Tongkat Ali, Malaysian Ginseng, longjax, Cay Ba Binh, Pasak Bumi, Langir Siam, Tung Sawa", category_id: 14, slug: "eurycoma-longifolia-jack"},
  {name: "Evodia rutaecarpa", aka: "Wuzhuyu, Wu Zhu Yu, Wu Zhu Yu Tang, Evodiae Fructus, Evodia Fruit, Evodia Fructae", category_id: 4, slug: "evodia-rutaecarpa"},
  {name: "Evolvulus alsinoides", aka: "Dwarf Morning Glory, Shankhapushpi", category_id: 7, slug: "evolvulus-alsinoides"},
  {name: "Fadogia agrestis", aka: "bakin gagai, black aphrodisiac", category_id: 20, slug: "fadogia-agrestis"},
  {name: "Fennel Essential Oil", aka: "Fennel, fennel, Foeniculum vulgare", category_id: 12, slug: "fennel-essential-oil"},
  {name: "Fenugreek", aka: "Trigonella foecum-graecum, fenugreek seeds", category_id: 14, slug: "fenugreek"},
  {name: "Ferula asafoetida", aka: "Asant, Food of the gods, Jowani badian, Stinking gum, Devil's dung, Giant fennel, Hing, Mvuje, Anghuzeh, Stinkasant", category_id: 12, slug: "ferula-asafoetida"},
  {name: "Feverfew", aka: "Tanacetum parthenium, Wild Chamomile, Featherfew, Chrysanthemum parthenium, Matricaria parthenium, Pyrenthrum parthenium, Leucanthemum parthenium, mutterroot, midsummer daisy, nosebleed, Medieval Aspirin, 18th century Aspirin", category_id: 4, slug: "feverfew"},
  {name: "Fish Oil", aka: "Eicosapentaenoic Acid, EPA, Docosahexaenoic Acid, DHA, Omega-3 fatty acids, Omega-3, Omega 3, N-3 Fatty Acids", category_id: 4, slug: "fish-oil"},
  {name: "Folic Acid", aka: "Folate, Vitamin B9, Pteroyl L-glutamic acid", category_id: 11, slug: "folic-acid"},
  {name: "Fucoxanthin", aka: "Seaweed Extract, Undaria Pinnatifida, fuco, fucothin", category_id: 10, slug: "fucoxanthin"},
  {name: "GABA", aka: "Gamma-Aminobutyric Acid", category_id: 19, slug: "gaba"},
  {name: "Gamma Oryzanol", aka: "&gamma;-Oryzanol", category_id: 6, slug: "gamma-oryzanol"},
  {name: "Ganoderma lucidum", aka: "Reishi, Lingzhi, Yeongji, Mannamtake, 10, 000 years mushroom, Mushroom of Immortality, Antlered Reishi, Rokkaku-Reishi, Ganoderma spores", category_id: 2, slug: "ganoderma-lucidum"},
  {name: "Garcinia cambogia", aka: "Gambooge, Pazham Puzhi, Bitter Kola, Malabar tamarind, (-)-Hydroxycitric acid, HCA, Hydroxycitric acid", category_id: 10, slug: "garcinia-cambogia"},
  {name: "Garlic", aka: "Allium sativum, Vegetable Viagra, Da suan, Camphor of the poor, Lasun, Stinking Rose, Ail, Ajo", category_id: 6, slug: "garlic"},
  {name: "Ginger", aka: "Zingiber officinale Roscoe, Zingiberaceae", category_id: 12, slug: "ginger"},
  {name: "Ginkgo biloba", aka: "Tanakan, Tebonin, R&ouml;kan, Maidenhair, gingko", category_id: 7, slug: "ginkgo-biloba"},
  {name: "Glucosamine", aka: "", category_id: 5, slug: "glucosamine"},
  {name: "Glucuronolactone", aka: "Glucuronic Acid, Glucaro 1, 4-lactone, Glutarate", category_id: 8, slug: "glucuronolactone"},
  {name: "Glutamine", aka: "L-Glutamine", category_id: 12, slug: "glutamine"},
  {name: "Glutathione", aka: "", category_id: 4, slug: "glutathione"},
  {name: "Glycine", aka: "2-Aminoacetic acid", category_id: 11, slug: "glycine"},
  {name: "Grape Seed Extract", aka: "GSE, OPC-3, Oligomeric Procyanidins, Procyanidin", category_id: 4, slug: "grape-seed-extract"},
  {name: "Grape juice", aka: "", category_id: 6, slug: "grape-juice"},
  {name: "Grapefruit", aka: "", category_id: 10, slug: "grapefruit"},
  {name: "Green Coffee Extract", aka: "", category_id: 10, slug: "green-coffee-extract"},
  {name: "Green Tea Catechins", aka: "Camellia sinensis, Green Tea Extract, GTE", category_id: 4, slug: "green-tea-catechins"},
  {name: "Griffonia simplicifolia", aka: "", category_id: 17, slug: "griffonia-simplicifolia"},
  {name: "Guggul", aka: "Commiphora mukul, Commiphora Wightii, Guggulsterones, pregna-4, 17-diene-3, 16-dione", category_id: 10, slug: "guggul"},
  {name: "Gynostemma pentaphyllum", aka: "Southern Ginseng, Jiao Gu-lan, Giao-Co-Lam (Tea), jiaogulan", category_id: 13, slug: "gynostemma-pentaphyllum"},
  {name: "HMB", aka: "Hydroxy-MethylButyrate, beta-hydroxy-beta-methylbutyrate", category_id: 18, slug: "hmb"},
  {name: "Harpagophytum procumbens", aka: "Devil's Claw, Grapple plant, Duiwelsklou, Wood Spider", category_id: 5, slug: "harpagophytum-procumbens"},
  {name: "Hederagenin", aka: "", category_id: 7, slug: "hederagenin"},
  {name: "Hemp Protein", aka: "Hemp, Cannabis sativa, Hempseed meal", category_id: 18, slug: "hemp-protein"},
  {name: "Hesperidin", aka: "5, 7, 3'-trihydroxy-4'-methoxyflavanone, hesperitin-7-O-rutinoside, Hesperitin glycoside, glucosyl hesperidin, Vitamin P, hesperitin, G-hesperidin", category_id: 6, slug: "hesperidin"},
  {name: "Hibiscus macranthus", aka: "", category_id: 16, slug: "hibiscus-macranthus"},
  {name: "Hibiscus rosasinensis", aka: "China rose, Rose mallow, Chinese hibiscus, Jasun, Badsha pasant, Gurhal, Ghorawal", category_id: 4, slug: "hibiscus-rosasinensis"},
  {name: "Hibiscus sabdariffa", aka: "Roselle, Isakpa, Krachiap daeng, Sour Tea", category_id: 6, slug: "hibiscus-sabdariffa"},
  {name: "Higenamine", aka: "Norcoclaurine, 1-[(4-hydroxyphenyl)methyl]-1, 2, 3, 4-tetrahydroisoquinoline-6, 7-diol", category_id: 10, slug: "higenamine"},
  {name: "Holy Basil", aka: "Ocimum sanctum, Green Tulsi, Sacred Basil, Tulsi, Ocimum tenuiflorum", category_id: 14, slug: "holy-basil"},
  {name: "Hoodia gordonii", aka: "Hoodia, Veldkos, Slimming cactus, Trichocaulon gordonii, Stapelia gordonii", category_id: 10, slug: "hoodia-gordonii"},
  {name: "Hordenine", aka: "N, N-dimethyltyramine", category_id: 10, slug: "hordenine"},
  {name: "Horny Goat Weed", aka: "Epidemium, Herba Epimdii, Icariin, Yinyanghuo, Fairy Wings, Rowdy Lamb Herb", category_id: 14, slug: "horny-goat-weed"},
  {name: "Horse Chestnut", aka: "Aesculus hippocastanum, Conker tree, Rosskastanie, venostasin", category_id: 6, slug: "horse-chestnut"},
  {name: "Hovenia dulcis", aka: "Japanese Raisin Tree", category_id: 15, slug: "hovenia-dulcis"},
  {name: "Huperzine-A", aka: "(1R, 9S, 13E)-1-amino-13-ethylidene-11-methyl-6-azatricyclo- 7.3.1.0 2, 7 trideca-2(7), 3, 10-trien-5-on, Qian Ceng Ta (Huperzia Serrata)", category_id: 7, slug: "huperzine-a"},
  {name: "Hypericum perforatum", aka: "St. John's Wort", category_id: 17, slug: "hypericum-perforatum"},
  {name: "Idebenone", aka: "", category_id: 7, slug: "idebenone"},
  {name: "Inositol", aka: "Myoinositol, Cyclohexanehexol, 1, 2, 3, 4, 5, 6-cyclohexanehexol", category_id: 13, slug: "inositol"},
  {name: "Iodine", aka: "", category_id: 11, slug: "iodine"},
  {name: "Iron", aka: "", category_id: 11, slug: "iron"},
  {name: "Irvingia gabonensis", aka: "African Wild Mango, African Mango Extract, African Bush Mango, Dika nut", category_id: 10, slug: "irvingia-gabonensis"},
  {name: "Isoleucine", aka: "", category_id: 18, slug: "isoleucine"},
  {name: "Japanese Knotweed", aka: "Polygonum Cuspidatum, Huzhang, Fleeceflower, Monkeyweed, itadori, Polygonum Japonicus, Kudzu", category_id: 6, slug: "japanese-knotweed"},
  {name: "Juniperus chinensis", aka: "byakushin", category_id: 10, slug: "juniperus-chinensis"},
  {name: "Kaempferia parviflora", aka: "Krachai Dum, Black Turmeric, Black Galingale, Thai Ginseng", category_id: 14, slug: "kaempferia-parviflora"},
  {name: "Kaempferol", aka: "", category_id: 4, slug: "kaempferol"},
  {name: "Kava", aka: "Piper methysticum, Kava Pepper, Ava Pepper, Kava Kava, Intoxicating Pepper, Awa, rauschpfeffer, sakau, tonga, wurzelstock, yangona", category_id: 17, slug: "kava"},
  {name: "Ketogenic diet", aka: "TKD, CKD, VLCKD, LCKD, keto", category_id: 10, slug: "ketogenic-diet"},
  {name: "King Oyster", aka: "Pleurotus eryngii, Eringi, King Brown", category_id: 4, slug: "king-oyster"},
  {name: "Kombucha", aka: "Fungal tea, Mushroom tea", category_id: 12, slug: "kombucha"},
  {name: "Krill Oil", aka: "Euphausiacea superba", category_id: 4, slug: "krill-oil"},
  {name: "L-Carnitine", aka: "Acetyl-L-Carnitine, ALCAR, Acetylcarnitine, L-Carnitine-L-Tartrate, LCLT, Glycine Propionyl-L-Carnitine, GPLC, Levocarnitine, Levacecarnine, L-3-hydroxytrimethylamminobutanoate, carnitine", category_id: 18, slug: "l-carnitine"},
  {name: "L-DOPA", aka: "Levodopa, L-3, 4-dihydroxyphenylalanine", category_id: 7, slug: "l-dopa"},
  {name: "L-Threonate", aka: "L-Threonic Acid", category_id: 7, slug: "l-threonate"},
  {name: "L-Tyrosine", aka: "", category_id: 17, slug: "l-tyrosine"},
  {name: "Lactobacillus casei", aka: "Yakult", category_id: 12, slug: "lactobacillus-casei"},
  {name: "Lactobacillus reuteri", aka: "ATCC PTA 6475, ATCC 55730, DSM 17938, NCIMB 30242", category_id: 12, slug: "lactobacillus-reuteri"},
  {name: "Lavender", aka: "", category_id: 17, slug: "lavender"},
  {name: "Leucic Acid", aka: "Alpha-Hydroxy-isocaproic acid, DL-alpha-Hydroxy-isocaproic acid, HICA", category_id: 18, slug: "leucic-acid"},
  {name: "Leucine", aka: "L-Leucine", category_id: 18, slug: "leucine"},
  {name: "Licorice", aka: "Licorice, Liquorice, Yashtimadhu, Glycyrrhiza, Glycyrrhiza Uralensis, Glycyrrhiza Glabra", category_id: 12, slug: "licorice"},
  {name: "Light Therapy", aka: "Light, Sunlight", category_id: 17, slug: "light-therapy"},
  {name: "Limonene", aka: "Lemon Extract, D-Limonene", category_id: 4, slug: "limonene"},
  {name: "Lutein", aka: "", category_id: 9, slug: "lutein"},
  {name: "Lysine", aka: "", category_id: 1, slug: "lysine"},
  {name: "Maca", aka: "Lepidium meyenii, Maca root, Peruvian Ginseng", category_id: 14, slug: "maca"},
  {name: "Magnesium", aka: "", category_id: 11, slug: "magnesium"},
  {name: "Magnolia officinalis", aka: "Saiboku-to, Magnolia Bark Extract, Honokiol, Magnolol", category_id: 17, slug: "magnolia-officinalis"},
  {name: "Manganese", aka: "", category_id: 5, slug: "manganese"},
  {name: "Mangifera indica", aka: "Common Mango", category_id: 12, slug: "mangifera-indica"},
  {name: "Marijuana", aka: "Cannabis Sativa, Weed, Medical Marijuana, Marihuana, dope, ganja, hashish, pot, Dronabinol (medical THC)", category_id: 17, slug: "marijuana"},
  {name: "Massularia acuminata", aka: "Pako Ijebu, Orin Ijebu", category_id: 14, slug: "massularia-acuminata"},
  {name: "Meditation", aka: "MBSR, mindfulness-meditation, sitting-practice", category_id: 17, slug: "meditation"},
  {name: "Medium-chain triglycerides", aka: "MCTs, MCT oil, medium-chain fatty acids", category_id: 7, slug: "medium-chain-triglycerides"},
  {name: "Melatonin", aka: "N-Acetyl-5-Methoxytryptamine, Melatonine, Melovine, Melatol, Melatonex, Circadin", category_id: 19, slug: "melatonin"},
  {name: "Melissa officinalis", aka: "Lemon Balm, Melissengeist, Bee balm, Garden Balm, Melissa, Erva-cidreira", category_id: 17, slug: "melissa-officinalis"},
  {name: "Methylsulfonylmethane", aka: "MSM, dimethyl sulfone, dimethylsulfone", category_id: 4, slug: "methylsulfonylmethane"},
  {name: "Microlactin", aka: "Hyperimmune Milk", category_id: 2, slug: "microlactin"},
  {name: "Milk Protein", aka: "", category_id: 18, slug: "milk-protein"},
  {name: "Milk Thistle", aka: "Marian thistle, Mary thistle, St Mary&rsquo;s thistle, Our Lady&rsquo;s thistle, Holy thistle, Sow thistle, Blessed Virgin thistle, Christ&rsquo;s crown, Venue thistle, Heal thistle, Variegated Thistle, Wild Artichoke, Carduus Marianus, Silybum marianum", category_id: 15, slug: "milk-thistle"},
  {name: "Minoxidil", aka: "Rogaine", category_id: 1, slug: "minoxidil"},
  {name: "MitoQ", aka: "{10-(4, 5-dimethoxy-2-methyl-3, 6-dioxo-1, 4-cycloheexadienlyl) decyl triphenylphosphonium methanesulfonate}, mitoquinone mesylate", category_id: 7, slug: "mitoq"},
  {name: "Modafinil", aka: "2-[(Diphenylmethyl) sulfinyl]acetamide, Provigil, Modalert, Modapro, Alertex", category_id: 7, slug: "modafinil"},
  {name: "Molybdenum", aka: "", category_id: 11, slug: "molybdenum"},
  {name: "Moringa oleifera", aka: "Moringa pterygosperma, Ben Oil Tree, Horse Radish Tree, Tree of Life, Miracle Tree, Drumstick Tree, Jiksna gandha, Akshiva, Mochak, Sahijan, Zogale", category_id: 4, slug: "moringa-oleifera"},
  {name: "Morus alba", aka: "White Mulberry, Karayamaguwa, Sohakuhi, Sang-Bai-Pi, Ramulus Mori", category_id: 7, slug: "morus-alba"},
  {name: "Mucuna pruriens", aka: "Velvet Bean, Cowitch, Werepe, Karara, Agbara", category_id: 7, slug: "mucuna-pruriens"},
  {name: "Muira puama", aka: "Potency Wood", category_id: 7, slug: "muira-puama"},
  {name: "Myricetin", aka: "3, 3', 4', 5, 5', 7-hexahydroxyflavone", category_id: 5, slug: "myricetin"},
  {name: "N-Acetylcysteine", aka: "N-Acetyl Cysteine, NAC, N-Ac", category_id: 4, slug: "n-acetylcysteine"},
  {name: "Nardostachys jatamansi", aka: "Spikenard, Jatamansi, Muskroot, Nardostachys grandiflora (synonym)", category_id: 17, slug: "nardostachys-jatamansi"},
  {name: "Nattokinase", aka: "Natto extract, subtilisin NAT, Orokinase, NSK-SD", category_id: 6, slug: "nattokinase"},
  {name: "Nefiracetam", aka: "DM-9384, N-(2, 6-dimethylphenyl)-2-(2-oxopyrrolidine-1-yl)-acetamide", category_id: 7, slug: "nefiracetam"},
  {name: "Nelumbo nucifera", aka: "Sacred Lotus, Indian Lotus, Bean of India", category_id: 17, slug: "nelumbo-nucifera"},
  {name: "Nicotine", aka: "", category_id: 7, slug: "nicotine"},
  {name: "Nigella sativa", aka: "Nigella cretica, Black cumin, Black seeds, Roman coriander, Nutmeg flower, Fennel flower, Ajaji", category_id: 2, slug: "nigella-sativa"},
  {name: "Nitrate", aka: "Beetroot extract", category_id: 6, slug: "nitrate"},
  {name: "Noopept", aka: "N-phenylacetyl-L-prolylglycine ethyl ester, Noopeptide, &#1053;&#1086;&#1086;&#1087;&#1077;&#1087;&#1090;, GVS-111", category_id: 7, slug: "noopept"},
  {name: "Nutmeg", aka: "Myristica Fragrans", category_id: 4, slug: "nutmeg"},
  {name: "Octopamine", aka: "Norsynephrine, p-hydroxyphenylethanolamine, &beta;-hydroxytyramine, Norphen, Norsympatol, norfenefrine", category_id: 7, slug: "octopamine"},
  {name: "Oleamide", aka: "Cerebrodiene", category_id: 19, slug: "oleamide"},
  {name: "Oleoylethanolamide", aka: "OEA, NOPE (a precursor)", category_id: 10, slug: "oleoylethanolamide"},
  {name: "Olive Oil", aka: "EVOO (Extra-Virgin Olive Oil)", category_id: 11, slug: "olive-oil"},
  {name: "Olive leaf extract", aka: "Olive polyphenols", category_id: 4, slug: "olive-leaf-extract"},
  {name: "Ophiopogon japonicus", aka: "Dragon's Beard, Mondo grass, Fountain plant, Monkey grass", category_id: 4, slug: "ophiopogon-japonicus"},
  {name: "Origanum vulgare", aka: "Oregano, Oil of Oregano, Wild Marjoram", category_id: 2, slug: "origanum-vulgare"},
  {name: "Ornithine", aka: "L-Ornithine", category_id: 18, slug: "ornithine"},
  {name: "Orthosiphon stamineus", aka: "Java, Misai kucing, Kumis kucing, cats whiskers, rau meo, cay bac, remujung, moustaches de chat, yaa nuat maeo", category_id: 4, slug: "orthosiphon-stamineus"},
  {name: "Oxaloacetate", aka: "OAA, 3-carboxy-3-oxopropanoic acid", category_id: 3, slug: "oxaloacetate"},
  {name: "Oxiracetam", aka: "4-hydroxy-2-oxo-pyrrolidinoacetamide, ISF-2522", category_id: 7, slug: "oxiracetam"},
  {name: "Oxytropis falcate", aka: "Edaxia, Locoweed (in reference to the Genus)", category_id: 2, slug: "oxytropis-falcate"},
  {name: "PRL-8-53", aka: "Methyl 3-(2-(benzyl(methyl)amino)ethyl)benzoate", category_id: 7, slug: "prl-8-53"},
  {name: "Paederia foetida", aka: "Prasarini, Akar Sekuntut, Gandhali", category_id: 4, slug: "paederia-foetida"},
  {name: "Palmatine", aka: "", category_id: 7, slug: "palmatine"},
  {name: "Panax ginseng", aka: "True Ginseng, Ginseng, Panax, Mountain Ginseng, Wild Ginseng", category_id: 7, slug: "panax-ginseng"},
  {name: "Patchouli", aka: "Pogostemon cablin, Patchouly, Patchy", category_id: 2, slug: "patchouli"},
  {name: "Paullinia cupana", aka: "Guarana, Guaran&aacute;, Brazilian cocoa", category_id: 8, slug: "paullinia-cupana"},
  {name: "Pedalium murex", aka: "Dakhani Gokhru, Bada Gokhru, Large caltrops, Yenugu palleru", category_id: 16, slug: "pedalium-murex"},
  {name: "Pelargonidin", aka: "Strawberry Anthocyanins", category_id: 4, slug: "pelargonidin"},
  {name: "Pelargonium sidoides", aka: "African Geranium, South African Geranium, Kaloban EPs7630, EPs 7630, Umckaloabo, rabas", category_id: 2, slug: "pelargonium-sidoides"},
  {name: "Peppermint", aka: "Menthol, Mentha piperita, Mentha balsamea", category_id: 12, slug: "peppermint"},
  {name: "Perilla Oil", aka: "", category_id: 4, slug: "perilla-oil"},
  {name: "Phellodendron amurense", aka: "Rutaceae, Amur Cork Tree, Kihada, Nexrutine, Corktree, Huangbai", category_id: 4, slug: "phellodendron-amurense"},
  {name: "Phenylethylamine", aka: "PEA, &beta;-phenylethylamine, phenethylamine, &beta;-phenethylamine, Benzeneethanamine", category_id: 7, slug: "phenylethylamine"},
  {name: "Phenylpiracetam", aka: "Phenotropil, Carphedon, (RS)-2-(2-oxo-4-phenylpyrrolidin-1-yl)acetamide", category_id: 7, slug: "phenylpiracetam"},
  {name: "Phosphatidylcholine", aka: "PC", category_id: 7, slug: "phosphatidylcholine"},
  {name: "Phosphatidylserine", aka: "PS", category_id: 7, slug: "phosphatidylserine"},
  {name: "Piceatannol", aka: "Astringinin", category_id: 4, slug: "piceatannol"},
  {name: "Picrorhiza kurroa", aka: "Kutki, Picrorhiza scrophulariiflora, Katuki, Kurro, Kutkin, Picroliv, Picrolax", category_id: 15, slug: "picrorhiza-kurroa"},
  {name: "Pine Pollen", aka: "Pinus sylvestris, scots pine, scotch pine, scotch fir", category_id: 4, slug: "pine-pollen"},
  {name: "Piracetam", aka: "Pyracetam, Pyrrolidone acetamide, 2-Oxo-1-pyrrolidine, Memotopril, Fezam (with cinnarizine), UCB6215", category_id: 7, slug: "piracetam"},
  {name: "Policosanol", aka: "Cane Sugar Extract", category_id: 6, slug: "policosanol"},
  {name: "Polygala tenuifolia", aka: "Yuan Zhi, Chinese Senega", category_id: 7, slug: "polygala-tenuifolia"},
  {name: "Polypodium leucotomos", aka: "Phlebodium aureum, Golden Polybody, Cabbage palm fern, Golden serpent fern, Calaguala, Anapsos", category_id: 1, slug: "polypodium-leucotomos"},
  {name: "Pomegranate", aka: "Pomegranates", category_id: 4, slug: "pomegranate"},
  {name: "Potassium", aka: "", category_id: 11, slug: "potassium"},
  {name: "Pramiracetam", aka: "CI-879, Diisoprop-yl-(2-oxopyrrolidin-1-yl)acetamide, CI879", category_id: 7, slug: "pramiracetam"},
  {name: "Prickly Pear Fruit", aka: "Opuntia ficus-indica, Cactus Pear Fruit, Sicilian Prickly Pear, Prickly pear, Nopal cactus", category_id: 6, slug: "prickly-pear-fruit"},
  {name: "Psoralea corylifolia", aka: "Bu Gu Zhi, Babchi, Babechi, Kushtanashini, Fountain bush, West Indian Satinwood, Somaraji, Bakuchi, Ravoli", category_id: 21, slug: "psoralea-corylifolia"},
  {name: "Psyllium", aka: "Psyllium Husk, Psyllium Fiber, Metamucil (brand name), ispaghula, plantago psyllium, plantago ovata, plantago", category_id: 12, slug: "psyllium"},
  {name: "Pterostilbene", aka: "trans-3, 5-dimethoxy-4-hydroxystilbene, 3, 5-dimethoxy-4-hydroxystilbene", category_id: 4, slug: "pterostilbene"},
  {name: "Pueraria lobata", aka: "Kudzu, Gegen", category_id: 21, slug: "pueraria-lobata"},
  {name: "Pueraria mirifica", aka: "White Kwao Krua", category_id: 21, slug: "pueraria-mirifica"},
  {name: "Punicalagins", aka: "Pomegranate Extract, Punica Granatum L., Pomegranate Juice", category_id: 4, slug: "punicalagins"},
  {name: "Punicic Acid", aka: "Pomegranate Seed Oil", category_id: 4, slug: "punicic-acid"},
  {name: "Pycnogenol", aka: "Pine Bark Extract, Pine Bark Procyanidins, Procyanidins", category_id: 11, slug: "pycnogenol"},
  {name: "Pygeum", aka: "", category_id: 16, slug: "pygeum"},
  {name: "Pyritinol", aka: "Pyrithioxine, Encephabol (Brand Name)", category_id: 7, slug: "pyritinol"},
  {name: "Pyrroloquinoline quinone", aka: "PQQ, Methoxatin", category_id: 4, slug: "pyrroloquinoline-quinone"},
  {name: "Pyruvate", aka: "", category_id: 18, slug: "pyruvate"},
  {name: "Quercetin", aka: "Apple extract, 3, 4, 5, 7-pentahydroxylflavone", category_id: 4, slug: "quercetin"},
  {name: "Raspberry Ketone", aka: "4-(4-hydroxyphenyl) butan-2-one, p-hydroxybenzyl acetone", category_id: 10, slug: "raspberry-ketone"},
  {name: "Rauwolscine", aka: "Alpha-yohimbine, isoyohimbine", category_id: 10, slug: "rauwolscine"},
  {name: "Red Clover Extract", aka: "trifolium pratense, biochanin A, Formononetin Promensil (brand name), Menoflavon (brand name)", category_id: 21, slug: "red-clover-extract"},
  {name: "Red Yeast Rice", aka: "RYR", category_id: 6, slug: "red-yeast-rice"},
  {name: "Resveratrol", aka: "Red Wine Extract, 3, 5, 4&prime;-trihydroxystilbene", category_id: 4, slug: "resveratrol"},
  {name: "Rhamnus nakaharai", aka: "", category_id: 12, slug: "rhamnus-nakaharai"},
  {name: "Rhaponticum carthamoides", aka: "Maral Root, Rhaponticum, Russian leuzea, Leuzea carthamoides", category_id: 18, slug: "rhaponticum-carthamoides"},
  {name: "Rhodiola Rosea", aka: "Rosavin, Rosenroot, Rhodiola Rhizome, Golden Root, Arctic Root, Rhidola", category_id: 17, slug: "rhodiola-rosea"},
  {name: "Rooibos", aka: "Aspalathus linearis, Red Bush Tea", category_id: 4, slug: "rooibos"},
  {name: "Rose Essential Oil", aka: "Rose, Rosa damascena, Rosa alba, Rosa gallica, Rosa centifolia, Rose Oil", category_id: 17, slug: "rose-essential-oil"},
  {name: "Rose Hip", aka: "Rosa canina, Dog Rose, Cynosbati fructus, Fructae cynosbati", category_id: 5, slug: "rose-hip"},
  {name: "Rosmarinic Acid", aka: "Rosmarinus Officinalis Extract, Rosemary Extract, Perilla Frutescens extract. Perilla Extract", category_id: 4, slug: "rosmarinic-acid"},
  {name: "Royal Jelly", aka: "", category_id: 4, slug: "royal-jelly"},
  {name: "Rubus coreanus", aka: "Korean Black Raspberry, Rubus tokkura, Cha tian pao, bokbunja, Rubi Fructus", category_id: 4, slug: "rubus-coreanus"},
  {name: "Rubus suavissimus", aka: "Chinese sweet leaf tea, Ten-cha", category_id: 10, slug: "rubus-suavissimus"},
  {name: "Ruscus aculeatus", aka: "Butcher's Broom, Jew's Myrtle, Knee Holly, Kneeholm, Pettigree, Sweet Broom", category_id: 6, slug: "ruscus-aculeatus"},
  {name: "S-Adenosyl Methionine", aka: "SAME, SAMe, Ademethionine, S-adenosyl-L-methionine, Adomet", category_id: 5, slug: "s-adenosyl-methionine"},
  {name: "Safflower Oil", aka: "Carthamus tinctorius", category_id: 6, slug: "safflower-oil"},
  {name: "Saffron", aka: "Crocus sativus", category_id: 17, slug: "saffron"},
  {name: "Salacia reticulata", aka: "Kothala himbutu", category_id: 13, slug: "salacia-reticulata"},
  {name: "Salvia hispanica", aka: "Chia seeds, Mexican chia, Salba", category_id: 12, slug: "salvia-hispanica"},
  {name: "Salvia miltiorrhiza", aka: "Danshen", category_id: 6, slug: "salvia-miltiorrhiza"},
  {name: "Salvia sclarea", aka: "Clary Sage", category_id: 17, slug: "salvia-sclarea"},
  {name: "Sarcosine", aka: "N-methylgycine, Methylglycine", category_id: 17, slug: "sarcosine"},
  {name: "Saw Palmetto", aka: "Serenoa Repens", category_id: 16, slug: "saw-palmetto"},
  {name: "Sceletium tortuosum", aka: "Kanna, Channa, Kougoed", category_id: 17, slug: "sceletium-tortuosum"},
  {name: "Schisandra chinensis", aka: "Omija, Omija Cha, Gomishi, Repnihat, Wuweizi, Lemonwood, Northern Magnolia Vine, Chinese Magnolia Vine, Matsbouza", category_id: 18, slug: "schisandra-chinensis"},
  {name: "Schizonepeta tenuifolia", aka: "Japanese Catnip, Schizonepeta, Jing Jie, Hyung-gae", category_id: 4, slug: "schizonepeta-tenuifolia"},
  {name: "Scutellaria baicalensis", aka: "Skullcap, Huang qin, Scutellariae radix, goldenroot, oroxylin A, baicalin", category_id: 4, slug: "scutellaria-baicalensis"},
  {name: "Sea Buckthorn", aka: "Hippophae rhamnoides", category_id: 4, slug: "sea-buckthorn"},
  {name: "Selenium", aka: "", category_id: 11, slug: "selenium"},
  {name: "Senna alexandrina", aka: "Senna alexandrina, Daio", category_id: 12, slug: "senna-alexandrina"},
  {name: "Serrapeptase", aka: "Serratiopeptidase, Serratia E-15, serralysin, serratiaprotease, Serratiopeptidase, Silk worm enzymes", category_id: 4, slug: "serrapeptase"},
  {name: "Sesamin", aka: "", category_id: 4, slug: "sesamin"},
  {name: "Shilajit", aka: "Mineral Pitch, Jew's Pitch, Mineral Wax, Salajeet, Brag-shun, Shilajita, Moomio, Mumie, Mumijo, Mumiyo", category_id: 4, slug: "shilajit"},
  {name: "Silica", aka: "", category_id: 5, slug: "silica"},
  {name: "Silk Amino Acids", aka: "Sericin, SAA, SAAa", category_id: 1, slug: "silk-amino-acids"},
  {name: "Simmondsia chinensis", aka: "Jojoba", category_id: 1, slug: "simmondsia-chinensis"},
  {name: "Sodium Bicarbonate", aka: "Baking Soda, Bicarb, Bicarbonate", category_id: 18, slug: "sodium-bicarbonate"},
  {name: "Sophora flavescens", aka: "Ku Shen, Kushen, Ku-Shen", category_id: 4, slug: "sophora-flavescens"},
  {name: "Soy Isoflavones", aka: "Genistein, Genistin, Daidzein, Daidzin, Equol, Dihydrogenistein, Dihydroglycitein, Glycitein, Glycitin", category_id: 21, slug: "soy-isoflavones"},
  {name: "Soy lecithin", aka: "", category_id: 11, slug: "soy-lecithin"},
  {name: "Sphaeranthus indicus", aka: "East Indian Globe Thistle, Mundi, Gorakhmundi, Kottakaranthai, Mahamundi", category_id: 4, slug: "sphaeranthus-indicus"},
  {name: "Spilanthes acmella", aka: "Jambu Oleoresin, Acmella oleracea, Spilanthes oleracea, toothache plant, paracress", category_id: 14, slug: "spilanthes-acmella"},
  {name: "Spirulina", aka: "", category_id: 11, slug: "spirulina"},
  {name: "Squalene", aka: "", category_id: 6, slug: "squalene"},
  {name: "Stephania tetrandra", aka: "hangfangji, Fangchi, Hang Fang Chi", category_id: 4, slug: "stephania-tetrandra"},
  {name: "Stevia", aka: "Rebiana, rebaudioside A, stevioside, steviol, steviol glycosides, sweetleaf, sugarleaf", category_id: 4, slug: "stevia"},
  {name: "Stinging Nettle", aka: "Urtica dioica, Radix Urticae, Common Nettle, Greater Nettle, Ortica, Tsuknida", category_id: 2, slug: "stinging-nettle"},
  {name: "Sulbutiamine", aka: "Arcalion, Enerion, Bisibuthiamine, Youvitan", category_id: 8, slug: "sulbutiamine"},
  {name: "Sulforaphane", aka: "Broccoli extract", category_id: 4, slug: "sulforaphane"},
  {name: "Sunifiram", aka: "DM-235", category_id: 4, slug: "sunifiram"},
  {name: "Synephrine", aka: "Bitter Orange, p-synephrine, Citrus Aurantium", category_id: 10, slug: "synephrine"},
  {name: "Syzygium aromaticum", aka: "Clove", category_id: 4, slug: "syzygium-aromaticum"},
  {name: "T3", aka: "Triiodothyronine, Liothyronine", category_id: 10, slug: "t3"},
  {name: "Taraxacum officinale", aka: "Dandelion, Dandelion extract, Pisselent, Piss-in-bed, priest's crown, lion's teeth, lion's tooth, milk daisy, huang hua di ding, dumble-dor, white endive, wild endive", category_id: 15, slug: "taraxacum-officinale"},
  {name: "Taurine", aka: "2-aminoethane sulphonic acid, L-Taurine", category_id: 4, slug: "taurine"},
  {name: "Tauroursodeoxycholic Acid", aka: "TUDCA", category_id: 15, slug: "tauroursodeoxycholic-acid"},
  {name: "Tea (Camellia Sinensis)", aka: "Green Tea, Black Tea, White Tea, Oolong Tea", category_id: 11, slug: "tea-camellia-sinensis"},
  {name: "Terminalia arjuna", aka: "Arjuna, Dhavala, Kakubha, Nadisarja, Veeravriksha, Partha, Indradru", category_id: 6, slug: "terminalia-arjuna"},
  {name: "Tetradecyl Thioacetic Acid", aka: "TTA", category_id: 10, slug: "tetradecyl-thioacetic-acid"},
  {name: "Theacrine", aka: "1, 3, 7, 9-tetramethyluric acid", category_id: 8, slug: "theacrine"},
  {name: "Theaflavins", aka: "", category_id: 12, slug: "theaflavins"},
  {name: "Theanine", aka: "L-Theanine, 5-N-Ethyl-Glutamine", category_id: 17, slug: "theanine"},
  {name: "Tinospora cordifolia", aka: "Guduchi, makabuhay, Amrita, Giloya, Giloe", category_id: 2, slug: "tinospora-cordifolia"},
  {name: "Trametes versicolor", aka: "Turkey Tail Mushroom, Coriolus versicolor, Polyporus versicolor", category_id: 2, slug: "trametes-versicolor"},
  {name: "Tribulus terrestris", aka: "Trib, puncturevine, protodioscin", category_id: 16, slug: "tribulus-terrestris"},
  {name: "Trichopus zeylanicus", aka: "Arogyappacha, Kerala Ginseng", category_id: 8, slug: "trichopus-zeylanicus"},
  {name: "Trimethylglycine", aka: "Betaine, TMG, Glycine betaine, oxyneurine", category_id: 18, slug: "trimethylglycine"},
  {name: "Tripterygium wilfordii", aka: "Thunder God Vine", category_id: 2, slug: "tripterygium-wilfordii"},
  {name: "Tulbaghia violacea", aka: "Wild Garlic, Sweet Garlic, Society Garlic, Wildeknoffel, Isihaqa", category_id: 2, slug: "tulbaghia-violacea"},
  {name: "Turmeric", aka: "Indian Curry, Curry extract", category_id: 12, slug: "turmeric"},
  {name: "Type-II Collagen", aka: "hydrolyzed collagen, solubilized collagen, CII, shark gelatin, gelatin, collagen", category_id: 5, slug: "type-ii-collagen"},
  {name: "Uncaria rhynchophylla", aka: "Uncariae uncis cum ramulus, Choto-ko, Choto-san, pulvis uncariae, Diao-teng-san, Gou-teng,", category_id: 7, slug: "uncaria-rhynchophylla"},
  {name: "Uncaria tomentosa", aka: "Cat's Claw, Vincaria", category_id: 8, slug: "uncaria-tomentosa"},
  {name: "Uridine", aka: "UDP, UMP", category_id: 7, slug: "uridine"},
  {name: "Ursolic Acid", aka: "Apple peel extract", category_id: 10, slug: "ursolic-acid"},
  {name: "Uva ursi", aka: "Arctostaphylos uva-ursi, bearberry, bear's grape, foxberry, crowberry, kinnikinnick, tinnick", category_id: 21, slug: "uva-ursi"},
  {name: "Valeriana officinalis", aka: "Valerian", category_id: 19, slug: "valeriana-officinalis"},
  {name: "Valine", aka: "", category_id: 15, slug: "valine"},
  {name: "Vanadium", aka: "", category_id: 13, slug: "vanadium"},
  {name: "Velvet Antler", aka: "Deer Velvet Antler, Deer Antler, Elk Velvet Antler, Cervus, Lu Jiao Pan", category_id: 16, slug: "velvet-antler"},
  {name: "Vinpocetine", aka: "Vincamine, Vinca Minor, Periwinkle Extract, Cavinton (Brand Name), ethyl apovincaminate", category_id: 7, slug: "vinpocetine"},
  {name: "Vitamin A", aka: "retinol, retinal, retinoic acid, tretinoin, beta-carotene", category_id: 11, slug: "vitamin-a"},
  {name: "Vitamin B1", aka: "Thiamine", category_id: 11, slug: "vitamin-b1"},
  {name: "Vitamin B2", aka: "Riboflavin", category_id: 11, slug: "vitamin-b2"},
  {name: "Vitamin B3 (Niacin)", aka: "Niacin, B3, Vitamin B3", category_id: 11, slug: "vitamin-b3-niacin"},
  {name: "Vitamin B5", aka: "Pantothenic acid, Panthenol, Pantothenate, Dexpanthenol, Pantothenylalcohol", category_id: 11, slug: "vitamin-b5"},
  {name: "Vitamin B6", aka: "pyridoxine, pyridoxamine, pyridoxal, pyridoxal phosphate, pyridoxal-5'-phosphate, PLP", category_id: 11, slug: "vitamin-b6"},
  {name: "Vitamin B₁₂", aka: "Cyanocobalamin, cobalamin, methylcobalamin, 5-deoxyadenosylcobalamin, adenosylcobalamin, cobamamide, dibencozide, hydroxocobalamin", category_id: 11, slug: "vitamin-b"},
  {name: "Vitamin C", aka: "Ascorbic Acid, Ascorbate, 2-oxo-L-threo-hexono-1, 4-lactone-2, 3-enediol, L-ascorbic acid", category_id: 11, slug: "vitamin-c"},
  {name: "Vitamin D", aka: "Cholecalciferol (Vitamin D3), Ergocalciferol (Vitamin D2)", category_id: 11, slug: "vitamin-d"},
  {name: "Vitamin E", aka: "Tocopherols, Tocotrienols", category_id: 11, slug: "vitamin-e"},
  {name: "Vitamin K", aka: "Phylloquinone, Menaquinone, MK-4, MK-7, Menatetrenone, Phytonadione", category_id: 11, slug: "vitamin-k"},
  {name: "Vitex agnus castus", aka: "Chaste Tree, VAC, Chasteberry", category_id: 21, slug: "vitex-agnus-castus"},
  {name: "Watercress", aka: "Nasturtium officinale", category_id: 4, slug: "watercress"},
  {name: "Whey Protein", aka: "whey, whey concentrate, whey isolate, whey hydrolysate, hydrolyzed whey, whey protein powder", category_id: 18, slug: "whey-protein"},
  {name: "White Kidney Bean Extract", aka: "Phaseolus Vulgaris, Phase 2 (Brand name)", category_id: 10, slug: "white-kidney-bean-extract"},
  {name: "Wine", aka: "Red Wine, White Wine, Nectar of the gods", category_id: 6, slug: "wine"},
  {name: "Yacon", aka: "Smallanthus sonchifolius, Yacon Syrup, Aicama, Jicama, Diet potato, yacon potato, yacon strawberry", category_id: 12, slug: "yacon"},
  {name: "Yamabushitake", aka: "Hericium erinaceus, Lion's Mane, Monkey's Head, Houtou (infrequent), Igelstachelbart, Pom Pom Blanc, Hedgehog Mushroom, Satyr&rsquo;s Beard", category_id: 7, slug: "yamabushitake"},
  {name: "Yerba mate", aka: "Ilex paraguariensis, Mate plant, St. Hilaire, Aquifoliaceae", category_id: 8, slug: "yerba-mate"},
  {name: "Yohimbine", aka: "Yohimbe, Corynanthe Yohimbe, Yohimbe Bark, Pausinystalia Yohimbe", category_id: 10, slug: "yohimbine"},
  {name: "ZMA", aka: "Zinc Magnesium Aspartate", category_id: 16, slug: "zma"},
  {name: "Zeaxanthin", aka: "", category_id: 9, slug: "zeaxanthin"},
  {name: "Zinc", aka: "", category_id: 11, slug: "zinc"},
  {name: "Ziziphus jujuba", aka: "Ziziphus Jujuba, Chinese Date, Da Zao, Jujube", category_id: 17, slug: "ziziphus-jujuba"},
  {name: "1,3-Dimethylamylamine", aka: "4-methylhexan-2-amine, DMAA, Dimethylamylamine, 1, 3-DMAA, Geranamine, Methylhexaneamine, 3-Dimethylpentylamine, Forthane", category_id: 8, slug: "1-3-dimethylamylamine"},
  {name: "2,4-Dinitrophenol", aka: "Dinitrophenol, DNP, 2, 4-DNP, Dinitro, Dinosan, Dnoc, Nitrophen, Chemox, Aldifen, Mitcal", category_id: 10, slug: "2-4-dinitrophenol"},
  {name: "5-HTP", aka: "5-hydroxytryptophan, serotonin precursor", category_id: 10, slug: "5-htp"},
  {name: "7,8-Dihydroxyflavone", aka: "7, 8-DHF", category_id: 7, slug: "7-8-dihydroxyflavone"},
  {name: "7-Keto DHEA", aka: "7-ketodehydroepiandrosterone, 7-oxodehydroepiandrosterone, 7-ketoDHEA, 7-oxoDHEA, 7-oxo, 7-keto", category_id: 10, slug: "7-keto-dhea"},
  {name: "NAD", aka: "B-DPNH, BNADH, Coenzyme 1, Enada, Nicotinamide Adénine Dinucléotide, Nicotinamide Adenine Dinucleotide Hydrate, Reduced DPN, Reduced Nicotinamide Adenine Dinucleotide", category_id: 3, slug: "nad"}
])
